import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex min-w-[512px] min-h-screen flex-col items-center justify-normal gap-4 p-24 bg-yellow-100/30">
          {children}
        </main>
      </body>
    </html>
  )
}
